name: Deployment of AWS Three Tier Architecture in Staging  Environment

description: This deployment pipeline is used for deployment of AWS Three Tier Architecture via Terraform in Staging Environment

on: 
    workflow_run:
        workflows: 
            - Deployment of AWS Three Tier Architecture in Test Environment
        types:
            - completed

permissions:
  id-token: write
  contents: read
  issues: write


concurrency:
  group: terraform-staging
  cancel-in-progress: false


jobs:
    
    terraform-plan-drift-check:
        if: ${{github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'workflow_dispatch'}}
        uses: ./.github/workflows/reusable-terraform-drift-check.yml
        with:
            execution-environment: staging
            commit_sha: ${{github.event.workflow_run.head_sha}}
        secrets: inherit

    terraform-plan-apply-if-no-drift:
        if: ${{github.event.workflow_run.conclusion == 'success' && needs.terraform-plan-drift-check.outputs.drift-check == '0'  }}
        needs: terraform-plan-drift-check
        uses: ./.github/workflows/reusable-terraform-plan-apply.yml
        with:
            execution-environment: staging
            commit_sha: ${{github.event.workflow_run.head_sha}}
        secrets: inherit

    terraform-check-resources:
        if: ${{github.event.workflow_run.conclusion == 'success'  }}
        needs: [terraform-plan-apply-if-no-drift]
        uses: ./.github/workflows/reusable-terraform-state-list.yml
        with:
            execution-environment: staging
            commit_sha: ${{github.event.workflow_run.head_sha}}
        secrets: inherit