name: Deployment of AWS Three Tier Architecture

description: This deployment pipeline is used for deployment of AWS Three Tier Architecture via Terraform i Development Environment

on: 
    push:
        branches:
            - master

        paths-ignore:
            - /Environments/Test/**
            - /Environments/Staging/**
            - /Environments/Production/**

    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    terraform-plan:
        uses: ./.github/workflows/reusable-terraform-plan.yml
        with:
          execution-environment: dev

