name: Deployment of AWS Three Tier Architecture

description: This deployment pipeline is used for deployment of AWS Three Tier Architecture via Terraform i Development Environment

on: 
    push:
        branches:
            - master

        paths-ignore:
            - Environments/Test/**
            - Environments/Staging/**
            - Environments/Production/**

    workflow_dispatch:
        inputs:
            perform-destroy:
                required: true
                type: boolean
                description: "Run terraform destroy after successful apply if user approves"

permissions:
  id-token: write
  contents: read
  issues: write


concurrency:
  group: terraform-dev
  cancel-in-progress: false


jobs:
    
    terraform-plan-drift-check:
        uses: ./.github/workflows/reusable-terraform-drift-check.yml
        with:
            execution-environment: dev
        secrets: inherit

    terraform-plan-apply-if-no-drift:
        needs: terraform-plan-drift-check
        if: ${{needs.terraform-plan-drift-check.outputs.drift-check == '0'}}
        uses: ./.github/workflows/reusable-terraform-plan-apply.yml
        with:
            execution-environment: dev
        secrets: inherit

    terraform-destroy:
        needs: terraform-plan-apply-if-no-drift
        if: ${{needs.terraform-plan-apply-if-no-drift.result == 'success' && ( (github.event_name == 'workflow_dispatch' && inputs.perform-destroy) || (github.event_name == 'push' && contains(github.event.head_commit.message, 'destroy')) ) }}
        uses: ./.github/workflows/reusable-terraform-destroy.yml
        with:
            execution-environment: dev
        secrets: inherit

    terraform-check-resources:
        needs: [terraform-plan-apply-if-no-drift, terraform-destroy]
        uses: ./.github/workflows/reusable-terraform-state-list.yml
        with:
            execution-environment: dev
        secrets: inherit