name: Deployment of AWS Three Tier Architecture

description: This deployment pipeline is used for deployment of AWS Three Tier Architecture via Terraform i Development Environment

on: 
    push:
        branches:
            - master

        paths-ignore:
            - /Environments/Test/**
            - /Environments/Staging/**
            - /Environments/Production/**

    workflow_dispatch:4

permissions:
  - read
  - write

jobs:
    terraform-plan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout-code
              uses: actions/checkout@v3

            - name: Setup-aws
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::806685982094:role/GitHubAuthentication
                aws-region: ap-south-1
            
            - name: setup-terraform
              uses: hashicorp/setup-terraform@v4
              with:
                terraform_version: ">= 1.13.0"
              






        
        
     