name: Deployment of AWS Three Tier Architecture in Test Environment

description: This deployment pipeline is used for deployment of AWS Three Tier Architecture via Terraform in Test Environment

on: 
    workflow_run:
        workflows: 
            - Deployment of AWS Three Tier Architecture in Dev Environment
        types:
            - completed

permissions:
  id-token: write
  contents: read
  issues: write


concurrency:
  group: terraform-test
  cancel-in-progress: false


jobs:
    
    terraform-plan-drift-check:
        if: ${{github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'workflow_dispatch'}}
        uses: ./.github/workflows/reusable-terraform-drift-check.yml
        with:
            execution-environment: test
            commit_sha: ${{github.event.workflow_run.head_sha}}
        secrets: inherit

    terraform-plan-apply-if-no-drift:
        if: ${{github.event.workflow_run.conclusion == 'success' && needs.terraform-plan-drift-check.outputs.drift-check == '0'  }}
        needs: terraform-plan-drift-check
        uses: ./.github/workflows/reusable-terraform-plan-apply.yml
        with:
            execution-environment: test
            commit_sha: ${{github.event.workflow_run.head_sha}}
        secrets: inherit

    terraform-check-resources:
        if: ${{github.event.workflow_run.conclusion == 'success'  }}
        needs: [terraform-plan-apply-if-no-drift]
        uses: ./.github/workflows/reusable-terraform-state-list.yml
        with:
            execution-environment: test
            commit_sha: ${{github.event.workflow_run.head_sha}}
        secrets: inherit

    terraform-show-website-url:
        runs-on: ubuntu-latest
        needs: terraform-plan-apply-if-no-drift 
        steps:
            - name: show-website-url
              run: |
                echo "WEBSITE URL IS ${{needs.terraform-plan-apply-if-no-drift.outputs.WEBSITE_URL}}"
                echo "WEBSITE URL IS ${{needs.terraform-plan-apply-if-no-drift.outputs.WEBSITE_URL}}" > website_url.txt

            - name: upload-website-url
              uses: actions/upload-artifact@v4
              with:
                name: WEBSITE_URL
                path: ${{ vars.TF_ENVIRONMENT }}/website_url.txt
                if-no-files-found: error