name: Manual Terraform destroy

description: This is a reusable workflow designed to run terrafrom destroy manually

on:
  workflow_dispatch:


    inputs:
        execution-environment:
          required: true
          type: choice
          default: dev
          options:
            - dev
            - test
            - staging
            - production
        confirm: 
            description: "Type DESTROY to confirm"

        

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
    manual-terraform-destroy:
        runs-on: ubuntu-latest

        environment: ${{inputs.execution-environment}}
        

        defaults:
          run:
            working-directory: ${{vars.TF_ENVIRONMENT}}

        env:
          TF_VAR_Environment   = ${{vars.TF_ENV}}
          TF_VAR_Application   = ${{vars.TF_APPLICATION}}
          TF_VAR_vpc_cidr      = ${{vars.TF_VPC_CIDR}}  
          TF_VAR_instance_type = ${{vars.TF_INSTANCE_TYPE}}
          TF_VAR_allowed_ports = ${{vars.TF_ALLOWED_PORTS}}
          TF_VAR_cidr_blocks   = ${{var.TF_CIDR_BLOCKS}}

        if: ${{inputs.confirm == 'DESTROY' && inputs.execution-environment != '' }}

        steps:

            - name: Checkout-code
              uses: actions/checkout@v4

            - name: Setup-aws
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{secrets.AWS_ARN}}
                aws-region: ap-south-1
            
            - name: setup-terraform
              uses: hashicorp/setup-terraform@v4
              with:
                terraform_version: ">= 1.13.0"

            - name: terraform-init
              run: terraform init -backend-config=${{inputs.execution-environment}}_backend.hcl

            - name: terraform-state-list
              run: terraform state list >> terraform-state.txt

            - name: upload-state-list
              uses: actions/upload-artifact@v4
              with:
                name: terraform-state
                path: ${{vars.TF_ENVIRONMENT}}/terraform-state.txt
                if-no-files-found: error
            
            
            - name: terraform-destroy
              if: ${{steps.terraform-state-list.outcome == 'success'}}
              run: terraform destroy -auto-approve