name: Resuabele Terraform Plan and Apply

description: This is a reusable workflow designed to initialise terraform and run terraform plan and upload the plan as an artifact

on:
  workflow_call:

    inputs:
       execution-environment:
         required: true
         type: string
       commit_sha:
          required: false
          type: string

    outputs:
      WEBSITE_URL:
        value: ${{jobs.terraform-plan-apply-reusable.outptus.WEBSITE_URL}}
      

jobs:
    terraform-plan-apply-reusable:
        runs-on: ubuntu-latest

        environment: ${{inputs.execution-environment}}
        

        defaults:
          run:
            working-directory: ${{vars.TF_ENVIRONMENT}}

        env:
          TF_VAR_Environment: ${{vars.TF_ENV}}
          TF_VAR_Application: ${{vars.TF_APPLICATION}}
          TF_VAR_vpc_cidr: ${{vars.TF_VPC_CIDR}}  
          TF_VAR_instance_type: ${{vars.TF_INSTANCE_TYPE}}
          TF_VAR_allowed_ports: ${{vars.TF_ALLOWED_PORTS}}
          TF_VAR_cidr_blocks: ${{vars.TF_CIDR_BLOCKS}}

        outputs:
          WEBSITE_URL: ${{steps.terraform-output.WEBSITE_URL}}

        steps:

            - name: Checkout-code
              uses: actions/checkout@v4
              with:
                ref: ${{ inputs.commit_sha || github.sha}}

            - name: Setup-aws
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{secrets.AWS_ARN}}
                aws-region: ap-south-1
            
            - name: setup-terraform
              uses: hashicorp/setup-terraform@v4
              with:
                terraform_version: ">= 1.13.0"

            - name: terraform-init
              run: terraform init -backend-config=${{inputs.execution-environment}}_backend.hcl

            - name: terraform-plan
              run: terraform plan -out=tfplan

            - name: terraform-plan-show
              run: |
                    terraform show tfplan > tfplan.txt


            - name: upload-tfplan-artifact
              uses: actions/upload-artifact@v4
              with:
                name: tfplan
                path: ${{ vars.TF_ENVIRONMENT }}/tfplan.txt
                if-no-files-found: error

            - name: terraform-apply
              id: terraform-apply
              run: terraform apply tfplan 

            - name: terraform-capture-output
              id: terraform-output
              run: |
                terraform output -json > tf_outputs.json
                echo "WEBSITE_URL=$(jq -r '.Public_ALB_DNS_Name.value')" >> $GITHUB_OUTPUT

